Database:
  UserName: root
  Password: root
  Host: 127.0.0.1
  Port: 3306
  Database: picture_design
  Charset: utf8mb4
  ParseTime: True
Server:
  RunMode: release
  HttpPort: 8000
  ClientIp: 127.0.0.1
  ReadTimeout: 60
  WriteTimeout: 60